parameters:
#    mesd_example_organizer.example.class: MESD\Example\OrganizerBundle\Example

services:
#    mesd_example_organizer.example:
#        class: %mesd_example_organizer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
